import 'package:get/get.dart';

class AppTranslations extends Translations {
  AppTranslations() {
    print('AppTranslations initialized');
  }

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'sign_in': 'Sign In',
      'sign_in_subtitle': 'Sign in to access your account',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'sign_up': 'Sign Up',
      'sign_up_subtitle': 'Sign up to access your account',
      'name': 'Name',
      'confirm_password': 'Confirm Password',
      'already_have_account': 'Already have an account?',
      'reset_password': 'Reset Password',
      'forgot_password_subtitle':
          'Enter the email used for your account and we\'ll send you a code for the confirmation',
      'enter_otp': 'Enter OTP',
      'otp_subtitle': 'we sent a 6 code to your email *****@.com',
      'didnt_get_otp': 'Didn\'t get OTP?',
      'resend': 'Resend',
      'verify': 'Verify',
      'create_new_password': 'Create New Password',
      'create_new_password_subtitle': 'Create a new unique password',
      'congratulations': 'Congratulations !',
      'success_msg':
          'Password Reset successful! You\'ll be redirected to the sign in screen now',
      'terms_conditions':
          'By using the app you agree to our Terms & Conditions and Privacy Policy',
      'no_internet': 'No Internet Connection',
      'server_error': 'Server Error',
      'welcome': 'Welcome',
      'good_morning': 'Good Morning',
      'learn_cook_enjoy': 'Learn, Cook & Enjoy!',
      'banner_desc':
          'Explore yummy recipes, unlock new dishes, and become a junior chef one meal at a time',
      'explore_recipes': 'Explore Recipes',
      'see_all': 'See All',
      'min': 'min',
      'servings': 'servings',
      'home': 'Home',
      'games': 'Games',
      'avatar': 'Avatar',
      'profile': 'Profile',
      'my_favourites': 'My Favourites',
      'favourite_empty_title': 'Your favourite list is empty!',
      'favourite_empty_subtitle':
          'Explore more recipes and add your favourite here.',
      'explore_recipe': 'Explore Recipe',
      'all_recipes': 'All Recipes',
      'failed_to_load_recipes': 'Failed to load recipes. Please try again.',
      // Search screen strings
      'search_hint': 'Pizza',
      'search_empty_title': 'Search for recipes',
      'search_empty_subtitle': 'Try searching for "Pizza", "Chicken", etc.',
      'no_results_title': 'No recipes found',
      'no_results_subtitle': 'Try a different search term',
      // Error messages
      'error': 'Error',
      'connectivity_check_failed': 'Failed to check network connectivity',
      'search_failed': 'Search failed. Please try again.',
      // Profile screen strings
      'my_profile': 'My Profile',
      'joined_since': 'Joined Since',
      'games_played': 'Games Played',
      'recipe_completed': 'Recipe Completed',
      'settings': 'Settings',
      'account_settings': 'Account Settings',
      'language': 'Language',
      'logout': 'Logout',
      'profile_photo': 'Profile Photo',
      'personal_information': 'Personal Information',
      'your_password': 'Your Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'cancel': 'Cancel',
      'save': 'Save',
      'select_language': 'Select Language',
      'change_language': 'Change Language',
      'logout_confirmation': 'Logout Confirmation',
      'logout_msg': 'Are you sure you want to logout?',
      // Avatar screen strings
      'hello_dehreen': 'Hello Dehreen!',
      'im_dwane': 'I\'m Dwane, How can I help you today?',
      'recommended_topics': 'Recommended Topics',
      'type_message': 'Type your message',
      'online': 'Online',
      'offline': 'Offline',
      'offline_msg': 'You are offline, please connect to the internet',
      'explore_all_games': 'Explore All Games',
      'crossword_puzzle': 'Crossword Puzzle',
      'word_search': 'Word Search',
      'games_coming_soon': 'Games screen coming soon',
      'ingredients_header': 'Ingredients',
      'review_button': 'Review',
      'views_count': 'views',
      'months_ago': 'months ago',
      'recipe_details': 'Recipe Details',
      // Ingredient popup strings
      'nutritional_info': 'Nutritional Information',
      'calories': 'Calories',
      'protein': 'Protein',
      'carbs': 'Carbs',
      'fat': 'Fat',
      'about_ingredient': 'About this ingredient',
      'health_benefits': 'Health Benefits',
      'substitution': 'Substitution',
      // Start Game screen strings
      'lets_started': "Let's Started!",
      'start_game_description': 'It will be fun to play this game and you can learn a lot from it',
      'start': 'Start',
      'game_title': 'Game',
      'retry': 'Retry',
      'done': 'Done',
      'empty_game_title': 'Name the Image:',
      'game_1_title': 'Game 1',
      'game_2_title': 'Game 2',
      'game_3_title': 'Game 3',
      'coming_soon': 'Coming Soon',
      'next_page_coming_soon': 'Next page is coming soon',
      'name_the_image': 'Name the Image:',
      // Game Finish screen strings
      'you_completed_game': 'You Completed the Game!',
      'back_to_games': 'Back to Games',
    },
  };
}
